# Generated by Django 5.0.14 on 2026-09-20 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+[1-9]\\d{7,14}$",
                        "Phone must be in international format, example +8801712345678",
                    )
                ],
            ),
        ),
    ]
