# Generated by Django 5.2.17 on 2026-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="posts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
